name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Run a one-line script
      run: echo Building raspberry pi os
    - name: Running a multi-line script
      run: |
          git clone --recurse-submodules https://github.com/arjuncr/raspberry-pi-os.git
          cd raspberry-pi-os
         ./build_rpi_os.sh --build-all
