name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install build dep
      run:  sudo apt install bison flex libelf-dev
    - name: Running Script to Create Minimal RPI-OS
      run: |
          git clone --recurse-submodules https://github.com/arjuncr/raspberry-pi-os.git
          cd raspberry-pi-os
         ./build_rpi_os.sh --build-all
         ./build_rpi_os.sh --create-rootfs
         ./build_rpi_os.sh --create-img
