name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v1
    
    - name: Run a one-line script
    
      run: echo Building raspberry pi os
      
    - name: Running a multi-line script
      run: |
          git clone --recurse-submodules https://github.com/arjuncr/raspberry-pi-os.git
         ./build_rpi_os.sh --build-all
